"""NFL Opponent Defense features — Phase 3 M2 (2026-07-22).

Aggregates weekly player stats INTO team-level opponent-defense
allowances. Answers questions like:
  • Passing yards allowed per game by DEN?
  • Fantasy points allowed to WR1s by BAL?
  • RB rushing TDs allowed by SF?
  • Sacks generated by PHI?

Storage-free: computes on-the-fly from `nfl_player_weekly`, which is
already loaded (2019-2025, 129k player-weeks). Cached to
`nfl_opp_defense_agg` after first computation per (season, team).

Position-specific matchup features are the most predictive input for
NFL props — DEN allowing 300+ pass yds/game to opposing QBs is a
much stronger buy signal than a raw offense-only projection.
"""

from __future__ import annotations

import logging
from statistics import mean
from typing import Optional

logger = logging.getLogger("lockscore.services.nfl_opp_defense")

_COLL_WEEKLY = "nfl_player_weekly"
_COLL_CACHE = "nfl_opp_defense_agg"


def _safe_mean(vals: list) -> Optional[float]:
    nums = [v for v in vals if isinstance(v, (int, float))]
    if not nums:
        return None
    return round(sum(nums) / len(nums), 2)


# ── Team-level defensive allowances by position ──────────────────────

async def team_defense_allowances(db, team: str, season: int,
                                  last_n_games: Optional[int] = None) -> dict:
    """Return per-game averages this defense has allowed by opposing position.

    If `last_n_games` is provided, only the L{n} games are used. Otherwise
    the full season-to-date.
    """
    coll = db[_COLL_WEEKLY]
    q = {
        "opponent_team": team,
        "season": season,
        "season_type": "REG",
    }
    if last_n_games:
        # find the L{n} unique game_ids this team has defended in
        recent_game_ids = set()
        async for r in coll.find(q, {"game_id": 1}).sort([("week", -1)]).limit(200):
            recent_game_ids.add(r.get("game_id"))
            if len(recent_game_ids) >= last_n_games:
                break
        q["game_id"] = {"$in": list(recent_game_ids)}

    # Aggregate by position of the opposing player
    pipe = [
        {"$match": q},
        {"$group": {
            "_id": "$position",
            "games_summed":  {"$addToSet": "$game_id"},
            "n_rows":        {"$sum": 1},
            "pass_yds":      {"$sum": "$passing_yards"},
            "pass_tds":      {"$sum": "$passing_tds"},
            "attempts":      {"$sum": "$attempts"},
            "completions":   {"$sum": "$completions"},
            "sacks":         {"$sum": "$sacks_suffered"},
            "rush_yds":      {"$sum": "$rushing_yards"},
            "rush_tds":      {"$sum": "$rushing_tds"},
            "carries":       {"$sum": "$carries"},
            "rec_yds":       {"$sum": "$receiving_yards"},
            "rec_tds":       {"$sum": "$receiving_tds"},
            "receptions":    {"$sum": "$receptions"},
            "targets":       {"$sum": "$targets"},
            "fp_ppr":        {"$sum": "$fantasy_points_ppr"},
        }},
    ]

    out_by_pos: dict[str, dict] = {}
    async for r in coll.aggregate(pipe):
        pos = r.get("_id") or "UNK"
        games = len(r.get("games_summed") or [])
        if games == 0:
            continue
        out_by_pos[pos] = {
            "games":              games,
            "pass_yds_per_game":  round((r.get("pass_yds") or 0) / games, 1),
            "pass_tds_per_game":  round((r.get("pass_tds") or 0) / games, 2),
            "pass_att_per_game":  round((r.get("attempts") or 0) / games, 1),
            "comp_per_game":      round((r.get("completions") or 0) / games, 1),
            "sacks_per_game":     round((r.get("sacks") or 0) / games, 2),
            "rush_yds_per_game":  round((r.get("rush_yds") or 0) / games, 1),
            "rush_tds_per_game":  round((r.get("rush_tds") or 0) / games, 2),
            "carries_per_game":   round((r.get("carries") or 0) / games, 1),
            "rec_yds_per_game":   round((r.get("rec_yds") or 0) / games, 1),
            "rec_tds_per_game":   round((r.get("rec_tds") or 0) / games, 2),
            "receptions_per_game": round((r.get("receptions") or 0) / games, 1),
            "targets_per_game":   round((r.get("targets") or 0) / games, 1),
            "fp_ppr_per_game":    round((r.get("fp_ppr") or 0) / games, 1),
        }
    return out_by_pos


# ── TD allowed by position ───────────────────────────────────────────

async def team_tds_allowed_by_position(db, team: str, season: int) -> dict:
    """Total TDs (rush + rec + pass) allowed by position group."""
    coll = db[_COLL_WEEKLY]
    pipe = [
        {"$match": {
            "opponent_team": team,
            "season": season,
            "season_type": "REG",
        }},
        {"$group": {
            "_id": "$position",
            "total_tds": {"$sum": {"$add": [
                {"$ifNull": ["$rushing_tds", 0]},
                {"$ifNull": ["$receiving_tds", 0]},
                {"$ifNull": ["$passing_tds", 0]},
            ]}},
            "games": {"$addToSet": "$game_id"},
        }},
        {"$project": {
            "position": "$_id",
            "total_tds": 1,
            "games": {"$size": "$games"},
            "tds_per_game": {"$round": [
                {"$cond": [
                    {"$eq": [{"$size": "$games"}, 0]},
                    0,
                    {"$divide": ["$total_tds", {"$size": "$games"}]},
                ]},
                3,
            ]},
            "_id": 0,
        }},
        {"$sort": {"tds_per_game": -1}},
    ]
    return {r["position"]: r async for r in coll.aggregate(pipe)}


# ── Overall team-level splits (all games this D has defended) ─────────

async def team_defense_summary(db, team: str, season: int) -> dict:
    """Return the top-line season-to-date summary for a defense."""
    coll = db[_COLL_WEEKLY]
    q = {"opponent_team": team, "season": season, "season_type": "REG"}
    game_ids = set()
    async for r in coll.find(q, {"game_id": 1}):
        game_ids.add(r.get("game_id"))
    n_games = len(game_ids)
    if not n_games:
        return {"games": 0, "team": team, "season": season}

    pipe = [
        {"$match": q},
        {"$group": {
            "_id": None,
            "pass_yds":     {"$sum": "$passing_yards"},
            "rush_yds":     {"$sum": "$rushing_yards"},
            "rec_yds":      {"$sum": "$receiving_yards"},
            "pass_tds":     {"$sum": "$passing_tds"},
            "rush_tds":     {"$sum": "$rushing_tds"},
            "rec_tds":      {"$sum": "$receiving_tds"},
            "ints":         {"$sum": "$passing_ints"},
            "sacks":        {"$sum": "$sacks_suffered"},
            "fp_ppr":       {"$sum": "$fantasy_points_ppr"},
        }},
    ]
    async for row in coll.aggregate(pipe):
        return {
            "team": team,
            "season": season,
            "games": n_games,
            "pass_yds_per_game":  round((row.get("pass_yds") or 0) / n_games, 1),
            "rush_yds_per_game":  round((row.get("rush_yds") or 0) / n_games, 1),
            "total_yds_per_game": round(((row.get("pass_yds") or 0) + (row.get("rush_yds") or 0)) / n_games, 1),
            "pass_tds_per_game":  round((row.get("pass_tds") or 0) / n_games, 2),
            "rush_tds_per_game":  round((row.get("rush_tds") or 0) / n_games, 2),
            "total_tds_per_game": round(((row.get("pass_tds") or 0) + (row.get("rush_tds") or 0) + (row.get("rec_tds") or 0)) / n_games, 2),
            "ints_forced_per_game":  round((row.get("ints") or 0) / n_games, 2),
            "sacks_per_game":      round((row.get("sacks") or 0) / n_games, 2),
            "fp_ppr_allowed_per_game": round((row.get("fp_ppr") or 0) / n_games, 1),
        }
    return {"games": 0}


# ── Position-rank fantasy points allowed table ────────────────────────
# The most commonly-used matchup indicator: how much fantasy PPR does
# this D allow to each position group vs the league average?

async def fantasy_points_allowed_by_position(db, season: int) -> dict:
    """League-wide table: for every team, fantasy pts PPR allowed to
    each position group. Enables rank-based matchup ratings
    ("DEN is the #2 easiest matchup for opposing QBs").
    """
    coll = db[_COLL_WEEKLY]
    q = {"season": season, "season_type": "REG"}
    pipe = [
        {"$match": q},
        {"$group": {
            "_id": {"team": "$opponent_team", "pos": "$position"},
            "fp":   {"$sum": "$fantasy_points_ppr"},
            "games": {"$addToSet": "$game_id"},
        }},
        {"$project": {
            "team": "$_id.team", "pos": "$_id.pos",
            "fp_per_game": {"$round": [
                {"$cond": [
                    {"$eq": [{"$size": "$games"}, 0]},
                    0,
                    {"$divide": ["$fp", {"$size": "$games"}]},
                ]},
                2,
            ]},
            "games": {"$size": "$games"},
            "_id": 0,
        }},
    ]
    table: dict[str, dict[str, float]] = {}
    async for r in coll.aggregate(pipe):
        team = r.get("team")
        pos = r.get("pos")
        if not team or not pos:
            continue
        table.setdefault(team, {})[pos] = {
            "fp_ppr_per_game": r["fp_per_game"],
            "games": r["games"],
        }
    # Add league-rank for each position
    all_positions = set()
    for team, per_pos in table.items():
        for p in per_pos.keys():
            all_positions.add(p)
    for pos in all_positions:
        # sort teams by fp_per_game descending (worst defense first)
        teams_sorted = sorted(
            [(team, table[team][pos]["fp_ppr_per_game"])
             for team in table if pos in table[team]],
            key=lambda x: -x[1],
        )
        for rank, (team, _) in enumerate(teams_sorted, start=1):
            table[team][pos]["league_rank_worst_first"] = rank
    return table


# ── Composite matchup factor ─────────────────────────────────────────

def matchup_factor(opp_allowances_pos: dict, prop_stat: str,
                   line: float) -> Optional[float]:
    """0.30-0.95 factor score for a player prop given opponent defense.

    Compares the opponent's per-game allowance for the position's stat
    vs the sportsbook line. E.g. line 199.5 pass yds and opponent
    allows 280 pass yds/game → factor 0.85 (very favorable).
    """
    if not opp_allowances_pos:
        return None
    stat_key_map = {
        "passing_yards":   "pass_yds_per_game",
        "attempts":        "pass_att_per_game",
        "passing_tds":     "pass_tds_per_game",
        "rushing_yards":   "rush_yds_per_game",
        "carries":         "carries_per_game",
        "rushing_tds":     "rush_tds_per_game",
        "receiving_yards": "rec_yds_per_game",
        "receptions":      "receptions_per_game",
        "receiving_tds":   "rec_tds_per_game",
        "targets":         "targets_per_game",
    }
    key = stat_key_map.get(prop_stat)
    if not key:
        return None
    allowed = opp_allowances_pos.get(key)
    if not isinstance(allowed, (int, float)):
        return None
    if line <= 0:
        return None
    ratio = allowed / line
    # 0.8x → factor 0.35, 1.0x → 0.60, 1.4x → 0.90
    if ratio >= 1.0:
        v = 0.60 + min(0.35, (ratio - 1.0) * 0.75)
    else:
        v = 0.35 + max(0.0, (ratio - 0.6)) * 0.625
    return round(max(0.30, min(0.95, v)), 3)


__all__ = [
    "team_defense_allowances",
    "team_tds_allowed_by_position",
    "team_defense_summary",
    "fantasy_points_allowed_by_position",
    "matchup_factor",
]
